### ISSUE TITLE
error of uploading output to s3 is silenced

### ISSUE THREAD

**Issue by byb121** [dockstore/s3cmd-plugin#2]
Hi,

I found that 'dockstore tool launch' will exit normally (exit 0) even uploading one of the outputs to s3 is failed, for example, due to wrong s3 path. I think in that case, ideally dockstore should exit non zero.

Thanks,

**Comment by denis-yuen** [comment]
Hi, 

What version of Dockstore and the S3 plugin was this with? 
This is the output I get with an incorrect S3 path with dockstore1.2.3 and the 0.0.3 S3 plugin. 
```
$ dockstore tool launch --local-entry Dockstore.cwl --json test.missing.s3.json
Creating directories for run of Dockstore launcher at: ./datastore//launcher-0b100bd4-8e07-4b63-8056-61d392e57c26
Provisioning your input files to your local machine
Downloading: #input_file from s3://oicr.temp/bamstats_report.zip into directory: /home/dyuen/dockstore_tools/dockstore-tool-md5sum/./datastore/launcher-0b100bd4-8e07-4b63-8056-61d392e57c26/inputs/87a7a1d4-cc13-473f-99db-eb1049c8b5d6
...
Provisioning your output files to their final destinations
Registering: #output_file to provision from /home/dyuen/dockstore_tools/dockstore-tool-md5sum/./datastore/launcher-0b100bd4-8e07-4b63-8056-61d392e57c26/outputs/md5sum.txt to : s3://oicr.temz/bamstats_report.zip
Calling on plugin io.dockstore.provision.S3Plugin$S3Provision to provision from /home/dyuen/dockstore_tools/dockstore-tool-md5sum/./datastore/launcher-0b100bd4-8e07-4b63-8056-61d392e57c26/outputs/md5sum.txt to s3://oicr.temz/bamstats_report.zip
Loading one->won
Loading two->two
10:37:35.972 [main] ERROR io.dockstore.common.FileProvisioning - plugin threw an exception
com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 273F95C33C96D12D)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1586)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1254)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4185)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4132)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1712)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:133)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:125)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:139)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: plugin threw an exception
$ echo $?
1
```

**Comment by byb121** [comment]
I was using Dockstore v1.2.3 with s3cmd plugin 0.0.5.

Yaobo

**Comment by byb121** [comment]
Hi,

Just wondering if the new commit to develop has solved this issue.

Thanks,

**Comment by garyluu** [comment]
@byb121 

https://artifacts.oicr.on.ca/artifactory/collab-release/io/dockstore/dockstore-file-s3cmd-plugin/0.0.6/dockstore-file-s3cmd-plugin-0.0.6.zip should have fixed this issue

**Comment by byb121** [comment]
Thanks.
